const getEnv = (key: string, fallback = ""): string =>
  process.env[key] ?? fallback;

export const ENV_VARIABLES = {
  NODE_ENV: getEnv("NODE_ENV", "development"),
  API_URL: getEnv("API_URL", getEnv("NEXT_PUBLIC_API_URL")),
  API_PROXY_PATH: getEnv("NEXT_PUBLIC_API_PROXY_PATH", ""),
  FORCE_ACCESS_TOKEN: getEnv("NEXT_PUBLIC_FORCE_ACCESS_TOKEN"),
  FORCE_REFRESH_TOKEN: getEnv("NEXT_PUBLIC_FORCE_REFRESH_TOKEN"),
  NEXTAUTH_URL: getEnv("NEXTAUTH_URL", "http://localhost:3009"),
  NEXTAUTH_SECRET: getEnv("NEXTAUTH_SECRET"),
  DEMO_EMAIL: getEnv("NEXT_PUBLIC_DEMO_EMAIL"),
  DEMO_PASSWORD: getEnv("NEXT_PUBLIC_DEMO_PASSWORD"),
  SUPABASE_URL: getEnv("NEXT_PUBLIC_SUPABASE_URL"),
  SUPABASE_ANON_KEY: getEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
  SUPABASE_SERVICE_ROLE_KEY: getEnv("SUPABASE_SERVICE_ROLE_KEY"),
  BUCKET_NAME: getEnv("NEXT_PUBLIC_SUPABASE_BUCKET", "hema"),
};
